spring:
  application:
   name: config-server
  cloud:
      config:
        enabled: true
        server:
            git: 
              uri: https://github.com/paweltechie/nelson-config-repo
              username: paweltechie
              password: TOja7832
#              searchPaths: /admin**,/league**
#            prefix: /config    
security:
  user:
    password: paweltechie
    name: TOja7832
server:
  port: 8888